"""Parameter inertness: the corpus is OPM (YM2151) but it is rendered on YM2612.

This is the piece that affects the headline figures, the paper's baseline and the
morph, so it is worth stating plainly.

The ``.opm`` files are VOPM format, which describes the **YM2151**. The render
happens on the **YM2612**, which is not the same chip, and the render protocol only
writes a subset of registers. The 56 corpus columns therefore fall into three
groups:

**Effective (38)** -- ``CON``, ``FL`` and per operator ``AR``, ``D1R``, ``D2R``,
``RR``, ``D1L``, ``TL``, ``KS``, ``MUL``, ``DT1``.

**Written but inert (6)** -- ``AMS``, ``PMS`` and the four ``AMS-EN``. They are
written to 0xB4 and 0x60, but the LFO is never enabled because the render protocol
declares ``lfo_enable: false`` and never sets register 0x22. With no LFO, amplitude
and pitch modulation do nothing.

**Never written (12)** -- ``LFRQ``, ``AMD``, ``PMD``, ``WF``, ``NFRQ``, ``PAN``,
``SLOT``, ``NE`` and the four ``DT2``. Several of these are not omissions but chip
differences: the YM2612 has no ``DT2``, and the noise generator behind
``WF``/``NFRQ``/``NE`` belongs to the YM2151. ``PAN`` is additionally neutralised
because 0xB4 is forced to 0xC0, i.e. output on both channels.

Why it matters, and it matters a lot
------------------------------------
1. **It inflates the unique-configuration count.** Two presets differing only in
   ``DT2`` or ``PAN`` produce exactly the same audio, yet they would count as
   distinct configurations and be rendered twice. Deduplication has to happen over
   the parameters that are relevant to the render.
2. **It unfairly handicaps the parameter baseline.** Including dimensions that
   demonstrably do not affect the audio they are compared against is a gift to a
   reviewer: "your parameter space performs badly because it contains pure noise".
   They have to be excluded, and the exclusion has to be stated.
3. **It wastes PCA components and morph controls.** A macro-control that moves
   ``DT2`` does nothing at all, and from the outside it just looks broken.

How it is resolved: an empirical audit
--------------------------------------
Reasoning about the code is not enough, it has to be **measured**. For each column,
vary its value over a sample of presets, re-render and compare the PCM hash. If the
audio never changes, the column is inert. Cheap, incontestable, and it produces a
table that doubles as corpus characterisation in the paper.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from .chip import GLOBAL_PARAMS, OPERATOR_NAMES, PER_OPERATOR_PARAMS


class Inertness(str, Enum):
    """Classification of a corpus column with respect to the rendered audio."""

    EFFECTIVE = "effective"
    WRITTEN_INERT = "written_inert"
    NEVER_WRITTEN = "never_written"
    NON_PARAMETER = "non_parameter"


# Columns that are not synthesis parameters at all.
#
# `Num` is an index within the source file and `Name` is autogenerated
# ("Instrument N"). Neither carries information, so both are kept for traceability
# and excluded from dedup, PCA and the baseline. The dataset card must say
# explicitly that `Name` is NOT an instrument label, so nobody uses it as one.
NON_PARAMETER_COLUMNS: tuple[str, ...] = ("Num", "Name", "Filename")

EXPECTED_EFFECTIVE: tuple[str, ...] = tuple(GLOBAL_PARAMS) + tuple(
    f"{op}_{param}" for op in OPERATOR_NAMES for param in PER_OPERATOR_PARAMS
)

# Written to the chip, but with no audible consequence under the declared render
# protocol because the LFO is never enabled.
EXPECTED_WRITTEN_INERT: tuple[str, ...] = ("AMS", "PMS") + tuple(
    f"{op}_AMS-EN" for op in OPERATOR_NAMES
)

# Never written at all. `reason` distinguishes a protocol choice from a genuine
# chip difference, which matters because only the former could be revisited.
EXPECTED_NEVER_WRITTEN: dict[str, str] = {
    "LFRQ": "LFO frequency; LFO is disabled by the render protocol",
    "AMD": "LFO amplitude depth; LFO is disabled",
    "PMD": "LFO pitch depth; LFO is disabled",
    "WF": "YM2151 noise/waveform control; does not exist on YM2612",
    "NFRQ": "YM2151 noise frequency; does not exist on YM2612",
    "NE": "YM2151 noise enable; does not exist on YM2612",
    "PAN": "neutralised: 0xB4 is forced to 0xC0, output on both channels",
    "SLOT": "VOPM slot mask; the protocol always keys all four slots",
    "M1_DT2": "DT2 does not exist on YM2612",
    "C1_DT2": "DT2 does not exist on YM2612",
    "M2_DT2": "DT2 does not exist on YM2612",
    "C2_DT2": "DT2 does not exist on YM2612",
}


@dataclass(frozen=True)
class ColumnClassification:
    column: str
    expected: Inertness
    reason: str


def expected_classification() -> dict[str, ColumnClassification]:
    """The a priori classification derived from the render protocol and the chip.

    This is the *hypothesis*. The audit measures it; disagreement between the two is
    a finding, not a formality, and it is reported rather than silently overwritten.
    """
    out: dict[str, ColumnClassification] = {}
    for col in EXPECTED_EFFECTIVE:
        out[col] = ColumnClassification(col, Inertness.EFFECTIVE, "written and audible")
    for col in EXPECTED_WRITTEN_INERT:
        out[col] = ColumnClassification(
            col,
            Inertness.WRITTEN_INERT,
            "written to the chip but inert because the LFO is never enabled",
        )
    for col, reason in EXPECTED_NEVER_WRITTEN.items():
        out[col] = ColumnClassification(col, Inertness.NEVER_WRITTEN, reason)
    for col in NON_PARAMETER_COLUMNS:
        out[col] = ColumnClassification(col, Inertness.NON_PARAMETER, "not a synthesis parameter")
    return out


def effective_columns() -> list[str]:
    """The columns used for dedup, the parameter baseline, PCA and the morph."""
    return list(EXPECTED_EFFECTIVE)


def inert_columns() -> list[str]:
    """Columns excluded from every modelling decision."""
    return list(EXPECTED_WRITTEN_INERT) + list(EXPECTED_NEVER_WRITTEN)


def summary() -> dict[str, int]:
    return {
        "effective": len(EXPECTED_EFFECTIVE),
        "written_inert": len(EXPECTED_WRITTEN_INERT),
        "never_written": len(EXPECTED_NEVER_WRITTEN),
        "non_parameter": len(NON_PARAMETER_COLUMNS),
    }
